-- DBA에서 실행해야 할거

-- GRANT CREATE ROLE TO TEAM8; -- TEAM8 계정에게 ROLE 권한 주기
-- GRANT SELECT ANY TABLE TO TEAM8;
-- GRANT GRANT ANY PRIVILEGE TO TEAM8;

-- BEGIN
--     FOR t IN (
--         SELECT table_name
--         FROM all_tables
--         WHERE owner = 'TEAM8'
--     ) LOOP
--         EXECUTE IMMEDIATE
--             'GRANT SELECT ON TEAM8.' || t.table_name ||
--             ' TO TEAM8 WITH GRANT OPTION';
--     END LOOP;
-- END;
-- /


CREATE ROLE ROLE_DOCTOR;
CREATE ROLE ROLE_RESEARCH;
CREATE ROLE ROLE_ADMIN;
CREATE ROLE ROLE_SYSTEM;

-- 시스템은 다 조회 가능
GRANT SELECT ANY TABLE TO ROLE_SYSTEM;

-- 의사 권한 : 모든 테이블 조회 가능
BEGIN
    FOR t IN (
        SELECT table_name
        FROM all_tables
        WHERE owner = 'TEAM8'
    ) LOOP
        EXECUTE IMMEDIATE
            'GRANT SELECT ON TEAM8.' || t.table_name || ' TO ROLE_DOCTOR';
    END LOOP;
END;
/

-- 연구자 권한 : 환자 테이블, caregiver 제외
BEGIN
    FOR t IN (
        SELECT table_name
        FROM all_tables
        WHERE owner = 'TEAM8'
    ) LOOP
        EXECUTE IMMEDIATE
            'GRANT SELECT ON TEAM8.' || t.table_name || ' TO ROLE_RESEARCH';
    END LOOP;
END;
/

REVOKE SELECT ON TEAM8.PATIENTS FROM ROLE_RESEARCH;
REVOKE SELECT ON TEAM8.CAREGIVER FROM ROLE_RESEARCH;

-- 행정직 : 전체 권한 제거 후 일부만 허용
GRANT SELECT ON TEAM8.ADMISSIONS TO ROLE_ADMIN;
GRANT SELECT ON TEAM8.ICUSTAYS TO ROLE_ADMIN;
GRANT SELECT ON TEAM8.SERVICES TO ROLE_ADMIN;
GRANT SELECT ON TEAM8.TRANSFERS TO ROLE_ADMIN;

-- 의사, 행정직, 연구원이 데이터 변형을 일으키지 않도록
REVOKE INSERT ANY TABLE FROM ROLE_DOCTOR;
REVOKE UPDATE ANY TABLE FROM ROLE_DOCTOR;
REVOKE DELETE ANY TABLE FROM ROLE_DOCTOR;

REVOKE INSERT ANY TABLE FROM ROLE_RESEARCH;
REVOKE UPDATE ANY TABLE FROM ROLE_RESEARCH;
REVOKE DELETE ANY TABLE FROM ROLE_RESEARCH;

REVOKE INSERT ANY TABLE FROM ROLE_ADMIN;
REVOKE UPDATE ANY TABLE FROM ROLE_ADMIN;
REVOKE DELETE ANY TABLE FROM ROLE_ADMIN;


SELECT * FROM session_privs;

CREATE USER TEAM8_SYSTEM_USER
IDENTIFIED BY "Oracle_4U!!12"
DEFAULT TABLESPACE TEAM8_TBS
QUOTA UNLIMITED ON TEAM8_TBS;

CREATE USER TEAM8_DOCTOR_USER
IDENTIFIED BY "Oracle_4U!!12"
DEFAULT TABLESPACE TEAM8_TBS
QUOTA UNLIMITED ON TEAM8_TBS;

CREATE USER TEAM8_ADMIN_USER
IDENTIFIED BY "Oracle_4U!!12"
DEFAULT TABLESPACE TEAM8_TBS
QUOTA UNLIMITED ON TEAM8_TBS;

CREATE USER TEAM8_RESEARCH_USER
IDENTIFIED BY "Oracle_4U!!12"
DEFAULT TABLESPACE TEAM8_TBS
QUOTA UNLIMITED ON TEAM8_TBS;

GRANT CREATE SESSION TO TEAM8_SYSTEM_USER;
GRANT CREATE SESSION TO TEAM8_DOCTOR_USER;
GRANT CREATE SESSION TO TEAM8_ADMIN_USER;
GRANT CREATE SESSION TO TEAM8_RESEARCH_USER;

GRANT ROLE_SYSTEM TO TEAM8_SYSTEM_USER;
GRANT ROLE_DOCTOR TO TEAM8_DOCTOR_USER;
GRANT ROLE_ADMIN TO TEAM8_ADMIN_USER;
GRANT ROLE_RESEARCH TO TEAM8_RESEARCH_USER;

select * from login_session;

-- 해당 테이블이 권한이 없는지 있는지 확인
SELECT 
    CASE 
        WHEN NOT EXISTS (
            SELECT 1
            FROM DBA_TAB_PRIVS
            WHERE OWNER = 'TEAM8'
              AND TABLE_NAME = 'PATIENTS'
              AND GRANTEE = 'TEAM8_ADMIN_USER'
        )
        THEN 'NO_PRIVILEGE'
        
        ELSE 'ACCESSIBLE'
    END AS RESULT
FROM dual;